[package]
name = "bpm-leptos"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
itertools = "0.14.0"
leptos = { version = "0.7.8", features = ["csr"] }
leptos-use = "0.15.7"
thiserror = "2.0.12"
web-time = "1.1.0"
